### ISSUE TITLE
README.md is missing a concrete list of supported Vulkan drivers

### ISSUE THREAD

**Issue by atomsymbol** [GPUOpen-LibrariesAndSDKs/Anvil#19]
From README.md:

> As such, it should (and has been verified to) work on any Linux/Windows Vulkan implementation.

What does "any" in "any Linux/Windows Vulkan implementation" mean?

**Comment by DominikWitczakAMD** [comment]
For internal testing purposes under Linux, we use our AMDGPU-PRO driver which can be found under http://support.amd.com/en-us/kb-articles/Pages/AMDGPU-PRO-Driver-for-Linux-Release-Notes.aspx. You can find the list of the Linux platforms the driver supports there.

We also verify the tool with another IHV's driver but I need to clarify that we do this only to ensure the library behaves as expected when executing on hardware with different set of capabilities and restrictions. In specific, our goal here is not to add work-arounds in the library for issues which occur due to bugs in third-party software, Users are free to propose such changes, as long as their modifications do not reduce performance or cause major interface changes.
