### ISSUE TITLE
Feature Request - Use Named Parameter Idiom

### ISSUE THREAD

**Issue by marti4d** [GPUOpen-LibrariesAndSDKs/Anvil#38]
Vulkan (and Anvil as a result) often have functions that require A LOT of parameters, some of which tend to be optional.

Since Vulkan uses a C API, it is very clear what each argument means (albeit overly verbose):

```
createParams.width = 1024;
createParams.height = 1024;
createParams.depth = 1;
createParams.numLayers = 1;
createParams.mipLevels = 1;
result = vkCreateThing(&createParams);
```

However, Anvil's wrappers lose this property.

```
// Gross, lots of magic numbers
Anvil::Thing::create(1024, 1024, 1, 1, 1); 

// Much-less gross, but comments can and will get messed up as devs make changes
Anvil::Thing::create(
    1024, // width
    1024,  // height
    1, // depth
    1, // numLayers
    1 // mipLevels
    ); 
```

By contrast, [NVidia's Vulkan C++][nvidia] wrappers already use the so-called [Named Parameter Idiom][faq], which would result in code that looks like this:

```
auto createParams = Anvil::Thing::CreateParams().width(1024).height(1024).depth(1)
    .numLayers(1).mipLevels(1);
result = Anvil::Thing::Create(createParams);
```

It would be nice to see Anvil take this approach as well, but of course it's a nice-to-have and not necessarily a deal breaker :)

[nvidia]: https://developer.nvidia.com/open-source-vulkan-c-api
[faq]: https://isocpp.org/wiki/faq/ctors#named-parameter-idiom

**Comment by DominikWitczakAMD** [comment]
First, I'd like to start the discussion by admitting I definitely see your point. The number of arguments that Vulkan structures expose can be overwhelming at times, and the fact you can't use sth along the lines of C#'s named arguments in C++ certainly does not help.

If you further take into account that Vulkan extensions often require apps to chain additional structures (implying even more arguments), things can quickly get out of control and start to look "gross" ;)

You quoted the named parameter idiom, which I had considered in the past when bringing up Anvil for its first public release. However, there is one huge issue about it which ultimately made me drop it and go the ugly way. Specifically, should

```
Anvil::Thing::CreateParams()
```

invocation assign any default values to Anvil::Thing? Two options here:

1. *No*. This implies we require the app to make a fair number of subsequent invocations which are then going to fill the struct with argument values. This also raises a question of how should optional structure chaining be supported with this idiom. Should we expose some sort of _chainXStructure()_ function which would take a separate _chainedStructArgs_ argument?

What should be the best way to inform the app it has not assigned values to all arguments? Assertion failure? If so, should it be debug build-only? Or maybe the abort you proposed in another ticket? Or maybe an app-specified callback for ultimate versability?

2. *Yes*. What default values should we be using in this case? Should we consider a solution where only certain parameters must be assigned values, and some can be left undefined?

I'm not stubborn on sticking to what currently works. Switching to this idiom would however imply breaking backwards compatibility so I'd prefer this decision to be made in a concious, well-thought manner.

**Comment by MaciejJesionowskiAMD** [comment]
I like the idea, but I'm afraid it might be challenging to implement in Anvil.

The reason it works so well in the mentioned example is because those builders work on objects that semantically behave just like the original Vulkan CreateInfo structs. They also map 1-to-1 to the Vulkan header and can easily be auto-generated.

Anvil on the other hand raises abstraction level and usually provides its own set of parameters that don't map directly to Vulkan API. This means all of this code would probably have to be hand-written, or you'd have to figure out on what data to base the auto-generation rules on (existing Anvil function prototypes?).

I think the named parameter idiom (or the builder pattern) works best if some default values can be assumed. This is what allows you to skip non-essential calls and reduce the clutter. But I wouldn't try to get too clever here, simply zero-initializing all parameters would be sufficient and practical. In this case emitting errors or warnings would probably be counter-intuitive to what we're trying to achieve.

**Comment by DominikWitczakAMD** [comment]
I'm growing more and more confident the right way to resolve this issue is by making all wrappers take a ptr to an ..Info struct instance, similar to what's already required when creating pipelines.

Any optional parameters could be set by invoking the struct's set_..() function, and the struct's ownership would be transferred over to the wrapper at instantiation time. 

This is becoming a pressing issue, as the features that will be shortly coming to Anvil further increase the number of parameters required to be specified at wrapper instantiation time. I'll be dealing with this one shortly.
