### ISSUE TITLE
Swapchain and RenderSurface should provide methods to get their current extents

### ISSUE THREAD

**Issue by marti4d** [GPUOpen-LibrariesAndSDKs/Anvil#43]
Currently in Anvil, the `Anvil::Swapchain` doesn't record the width and height it was created with, and the `Anvil::RenderSurface` caches the values it was created with, but they can change when the window is resized, and it provides no way to determine the current dimensions.

This is a problem, because detecting whether the swapchain needs to be resized is a matter of getting the current extent of the rendering surface and comparing it to the extent of the swapchain.

**Comment by DominikWitczakAMD** [comment]
Good one as well, thanks Chris.

Adding support for window resizing is on my TODO list, which is how this omission has sneaked in. Will try to get it addressed shortly.

**Comment by DominikWitczakAMD** [comment]
Since this issue is related to lack of support for window resizing, I've done a few things to indirectly address this issue:

1) The window creation logic has been adjusted so that it will now create non-scalable windows. There's no point in letting apps create scalable windows if there's no way to handle resize events.
2) Added extent getter to swapchain.
3) Modified extent getter's name in ```Anvil::Window``` to ```get_{height, width}_at_creation_time()``` to clarify these values are not obtained from the WM at call time.

All changes are going to land in the coming update.
