### ISSUE TITLE
Vulkan functions not being loaded

### ISSUE THREAD

**Issue by WarpspeedSCP** [GPUOpen-LibrariesAndSDKs/Anvil#85]
I've been trying to figure out why the build keeps failing with `error: ‘vkGetDeviceProcAddr’ was not declared in this scope`. I can't find the file in which the code for loading the vulkan functions is either. How are they loaded?

I'm new to cmake so I don't know if I did this right, but I added Anvil as an external project in my own cmakelists file and then added a link target to `libAnvil.so` and include paths for `anvil/include`. Is this the right way to do it? Or should I try to copy the way its done in the examples?

**Comment by DominikWitczakAMD** [comment]
The reason you're getting the linker error is because of missing dependencies.

This requirement is going to be removed at some point in the future, but at the moment Anvil needs to be linked with Vulkan SDK's library. One of the ways to make sure that happens is by configuring your project's CMake file to list Anvil as one of the libraries your executable should link with - that's what the examples do.

Alternatively, you can link with both the result Anvil static library *and* Vulkan SDK's. This should work just as fine.

**Comment by WarpspeedSCP** [comment]
Ah meant to say `libAnvil.a`, there.
